name: XGlowExample
main: ru.xezard.glow.example.GlowExamplePlugin
author: Xezard
website: xezard.me
version: ${project.parent.version}
api-version: 1.13
depend: [XGlow]

commands:
  glow:
    description: Main command
